language: haskell
install:
  - "cabal install code-builder/ rest-stringmap/ rest-client/ rest-core/ rest-example/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ rest-wai/ --dry-run -v3 --max-backjumps=-1 --reorder-goals"
script:
  - "cabal install code-builder/ rest-stringmap/ rest-client/ rest-core/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ rest-wai/ --max-backjumps=-1 --reorder-goals"
  - "cabal install rest-example/ -fhappstack --only-dependencies"
  - "cabal install rest-example/ -fhappstack --jobs=1"
  - "cabal install rest-example/ -fsnap --only-dependencies"
  - "cabal install rest-example/ -fsnap --jobs=1"
  - "cabal install rest-example/ -fwai --only-dependencies"
  - "cabal install rest-example/ -fwai --jobs=1"
  - "rest-example-gen --haskell --target rest-example/client"
  - "cabal install rest-example/client"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
